version: '3.8'

volumes:
  db_data:

services:
  db:
    container_name: database
    image: postgres
    volumes:
      - db_data/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  server-side:
    container_name: server-side
    build: ./server-side/
    command: bundle exec rails server -b 0.0.0.0
    image: server-side
    ports:
      - 3000:3000
    volumes:
      - ./server-side:/server-app
    tty: true
    stdin_open: true
    depends_on:
      - db
    links:
      - db

  client-side:
    container_name: client-side
    build: ./client-side/
    image: client-side
    ports:
      - 8000:8000
    volumes:
      - ./client-side:/client-app
      - /client-app/node_modules
    command: sh -c "yarn && yarn dev"