version: '3.8'

volumes:
  db_data:

services:
  db:
    image: postgres
    volumes:
      - db_data/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  server-side:
    build: ./server-side/
    command: bundle exec rails server -b 0.0.0.0
    image: server-side
    ports:
      - 3000:3000
    volumes:
      - ./server-side:/app
    tty: true
    stdin_open: true
    depends_on:
      - db
    links:
      - db